package edu.chinna.kadira;

public enum TestcaseDocEnum {
	IMAGES_FOLDER,
	QA_TESTING,
	TEST_CASE_FONT,
	QA_TESTING_RESULTS,
	TEST_CASE_SC,
	TEST_CASE_STATUS,
	TEST_CASE_ON,
	TEST_CASE_BLANK,
	SUMMARY_OF_CHANGE,
	STEPS_EXECUTED,
	TEST_CASE_RESULTS,
	TEST_CASE_CASE_NUM,
	TEST_CASE_LINE_SPEC,
	TEST_CASE_DOCUMENTATION,
	TEST_CASE_QA_DETAILS,
	TEST_CASE_PAGE,
	TEST_CASE_CURR_PAGE,
	TEST_CASE_OF,
	TEST_CASE_NUMPAGES
}
